### ISSUE TITLE
Guest can add items from multiple businesses into a single cart.

### ISSUE THREAD

**Issue by julyytran** [ThePivotHJJJ/the_pivot#11]
Guest bid on items from multiple businesses

As a guest user,
I click on view all shops
I click on shop 1
and I click on an item
and I bid on it
and then I return to view all shops
and I click on shop 2
and I click on an item 
and I bid on it

**Comment by julyytran** [comment]
Spec says this is a user story for guest, but it doesn't quite fit with our model

"As a guest customer, I should be able to add items from multiple businesses into a single cart."

**Comment by julsfelic** [comment]
I agree that we should get some clarification from Josh about this.

**Comment by hhoopes** [comment]
Should be able to bid/checkout directly from each seller, but could also have an option on a collector page (to retain shopping cart) to buy items that aren't bid on. Might go with "buy it now"

**Comment by julyytran** [comment]
So this story is for "buy it now" items

As a guest,
I visit all shops
and I click on shop 1
and I click on item 1
and I add it to my cart
and then I visit all shops
and I click on shop 2
and I click on item 2
and I add it to my cart
and then when I visit my cart,
I see item 1 and item 2
I see that item
