### ISSUE TITLE
Business admin can manage other business admins

### ISSUE THREAD

**Issue by julyytran** [ThePivotHJJJ/the_pivot#18]
As a business admin,
from my dashboard,
I click on "manage admins"
and I see a table of all the store admins
and I click "delete" for admin 2
and then I see a table of all the store admins, without admin 2 there

Is this what this story is looking for?

**Comment by julsfelic** [comment]
Is this story the idea that a business admin can also have other admins that can run the store?

**Comment by hhoopes** [comment]
That was my interpretation. I would also add the ability to make new admins (by username?), and perhaps a scenario as the sad case where a shop admin doesn't see admins for different shops in the list for their own.

**Comment by julyytran** [comment]
That was our thought. This came from the spec. Could use some clarification from Josh. I like the sad path, Heidi.

**Comment by hhoopes** [comment]
any admin can remove or add any admin for that store
