### ISSUE TITLE
Platform admin can approve/decline creation of new businesses

### ISSUE THREAD

**Issue by julyytran** [ThePivotHJJJ/the_pivot#25]
As a logged in platform admin,
from my dashboard,

Creation of new business its own page where platform admin can hit approve or deny,

OR

the table in the "Manage stores" page has a status column of online, offline, or pending, and if status is pending (meaning that creation request is pending) platform admin can click "approve request" or "deny request" next to that store

**Comment by julsfelic** [comment]
So I like the idea that:

Let's say a user wants to create a business. They go to their dashboard and go to create the  "store". From there, they have to wait for a platform admin approval before they can add items to their store.

On the admin platform side:

They would have a queue of pending store requests that they can approve of deny

**Comment by hhoopes** [comment]
As Julian suggests, sounds like there are other stories hinted at here, but I like the idea of a table that has pending/online/offline as 3 discrete statuses.

**Comment by hhoopes** [comment]
Store admin can potentially be able to edit store and add items before it's public, but to become visible requires approval from a platform admin
